module.exports = {
  name: 'MagicWeb Center',
  prefix: 'antdAdmin',
  footerText: 'Ant Design Admin  © 2017 zuiidea',
  logo: '/logo.png',
  iconFontCSS: '/iconfont.css',
  iconFontJS: '/iconfont.js',
  baseURL: 'http://localhost:8000/api/v1',
  YQL: ['http://www.zuimeitianqi.com'],
  CORS: ['http://localhost:7000'],
  openPages: ['/login'],
  apiPrefix: '/api/v1',
  api: {
    userLogin: '/user/login',
    userLogout: '/user/logout',
    userInfo: '/userInfo',
    users: '/users',
    user: '/user/:id',
    groups: '/groups',
    group: '/group/:id',
    articles: '/articles',
    article: '/article/:id',
    catalogs: '/groups',
    catalog: '/group/:id',
    links: '/groups',
    link: '/group/:id',
    medias: '/groups',
    media: '/group/:id',
    dashboard: '/dashboard',
  },
}
