module.exports = [
  {
    id: 1,
    icon: 'laptop',
    name: 'Dashboard',
    router: '/dashboard',
  },
  {
    id: 2,
    bpid: 1,
    name: '内容管理',
    icon: 'appstore-o',
    router: '/content',
  },
  {
    id: 21,
    bpid: 2,
    mpid: 2,
    name: '文章管理',
    icon: 'file-text',
    router: '/content/article',
  },
  {
    id: 211,
    mpid: -1,
    bpid: 21,
    name: '编辑文章',
    router: '/content/article/editor',
  },  
  {
    id: 212,
    mpid: -1,
    bpid: 21,
    name: '文章详情',
    router: '/content/article/:id',
  },
  {
    id: 22,
    bpid: 2,
    mpid: 2,
    name: '分类管理',
    icon: 'folder',
    router: '/content/catalog',
  },
  {
    id: 221,
    mpid: -1,
    bpid: 22,
    name: '分类详情',
    router: '/content/catalog/:id',
  },
  {
    id: 23,
    bpid: 2,
    mpid: 2,
    name: '链接管理',
    icon: 'link',
    router: '/content/link',
  },
  {
    id: 231,
    mpid: -1,
    bpid: 23,
    name: '链接详情',
    router: '/content/link/:id',
  },
   {
    id: 24,
    bpid: 2,
    mpid: 2,
    name: '文件管理',
    icon: 'file',
    router: '/content/media',
  },
  {
    id: 241,
    mpid: -1,
    bpid: 24,
    name: '文件详情',
    router: '/content/media/:id',
  },
  {
    id: 3,
    bpid: 1,
    name: '用户管理',
    icon: 'team',
  },
  {
    id: 31,
    bpid: 3,
    mpid: 3,
    name: '用户信息',
    icon: 'user',
    router: '/account/user',
  },
  {
    id: 311,
    mpid: -1,
    bpid: 31,
    name: '用户详情',
    icon: 'idcard',
    router: '/account/user/:id',
  },
  {
    id: 32,
    bpid: 3,
    mpid: 3,
    name: '分组信息',
    icon: 'tag-o',
    router: '/account/group',
  },
  {
    id: 321,
    mpid: -1,
    bpid: 32,
    name: '分组详情',
    icon: 'solution',
    router: '/account/group/:id',
  },
  {
    id: 4,
    bpid: 1,
    name: 'Request',
    icon: 'api',
    router: '/request',
  },
  {
    id: 5,
    bpid: 1,
    name: 'UI Element',
    icon: 'camera-o',
  },
  {
    id: 51,
    bpid: 5,
    mpid: 5,
    name: 'IconFont',
    icon: 'heart-o',
    router: '/UIElement/iconfont',
  },
  {
    id: 52,
    bpid: 5,
    mpid: 5,
    name: 'DataTable',
    icon: 'database',
    router: '/UIElement/dataTable',
  },
  {
    id: 53,
    bpid: 5,
    mpid: 5,
    name: 'DropOption',
    icon: 'bars',
    router: '/UIElement/dropOption',
  },
  {
    id: 54,
    bpid: 5,
    mpid: 5,
    name: 'Search',
    icon: 'search',
    router: '/UIElement/search',
  },
  {
    id: 55,
    bpid: 5,
    mpid: 5,
    name: 'Editor',
    icon: 'edit',
    router: '/UIElement/editor',
  },
  {
    id: 56,
    bpid: 5,
    mpid: 5,
    name: 'layer (Function)',
    icon: 'credit-card',
    router: '/UIElement/layer',
  },
  {
    id: 6,
    bpid: 1,
    name: 'Recharts',
    icon: 'code-o',
  },
  {
    id: 61,
    bpid: 6,
    mpid: 6,
    name: 'LineChart',
    icon: 'line-chart',
    router: '/chart/lineChart',
  },
  {
    id: 62,
    bpid: 6,
    mpid: 6,
    name: 'BarChart',
    icon: 'bar-chart',
    router: '/chart/barChart',
  },
  {
    id: 63,
    bpid: 6,
    mpid: 6,
    name: 'AreaChart',
    icon: 'area-chart',
    router: '/chart/areaChart',
  },
  {
    id: 7,
    bpid: 1,
    name: 'Test Navigation',
    icon: 'setting',
  },
  {
    id: 71,
    bpid: 7,
    mpid: 7,
    name: 'Test Navigation1',
    router: '/navigation/navigation1',
  },
  {
    id: 72,
    bpid: 7,
    mpid: 7,
    name: 'Test Navigation2',
    router: '/navigation/navigation2',
  },
  {
    id: 721,
    bpid: 72,
    mpid: 72,
    name: 'Test Navigation21',
    router: '/navigation/navigation2/navigation1',
  },
  {
    id: 722,
    bpid: 72,
    mpid: 72,
    name: 'Test Navigation22',
    router: '/navigation/navigation2/navigation2',
  },
]
